### PR TITLE
Update LTX09_gradio.py

### PR DESCRIPTION
**Pull request by Husky110**
using LTX newer version 0.9.1

### CODE REVIEW

**Comment by nitinmukesh** [comment]
This will not work for now. I already raised issue and they are working on adding support.

https://github.com/huggingface/diffusers/issues/10321
https://github.com/huggingface/diffusers/pull/10330

**Comment by newgenai79** [comment]
Closing for now as above.
New file need to be created as new Repo will be needed for 0.9.1 model.

**Comment by realenuf** [comment]
Any chance to support the new 0.96 and 0.96 distilled models, please?

**Comment by nitinmukesh** [comment]
@realenuf 

Please request here for new model support
https://github.com/huggingface/diffusers/issues/11359

**Pull request closed without merging**
